spring.application.name=evote-backend
spring.datasource.url=jdbc:mysql://localhost:3306/evote_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sao03OH@
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Security configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Server configuration
server.port=8081